const tags = [
	{ '_id': 'Adult Entertainmnent' },
	{ '_id': 'Celebrities & Entertainment News' },
	{ '_id': 'Comics' },
	{ '_id': 'Anime & Manga' },
	{ '_id': 'Cartoons' },
	{ '_id': 'Film & TV Industry' },
	{ '_id': 'Music Awards' },
	{ '_id': 'Record Labels' },
	{ '_id': 'Bars, Clubs & Nightlife' },
	{ '_id': 'Concerts & Music Festivals' },
	{ '_id': 'Event Ticket Sales' },
	{ '_id': 'Expos & Conventions' },
	{ '_id': 'Film Festivals' },
	{ '_id': 'Food & Beverage Events' },
	{ '_id': 'Live Sporting Events' },
	{ '_id': 'Movie Listings & Theater Showtimes' },
	{ '_id': 'Fun & Trivia' },
	{ '_id': 'Flash-Based Entertainment' },
	{ '_id': 'Humor' },
	{ '_id': 'Movies' },
	{ '_id': 'Animated Movies' },
	{ '_id': 'Bollywood & South Asian Film' },
	{ '_id': 'Silent Films' },
	{ '_id': 'DVD & Video Shopping' },
	{ '_id': 'Movie Memorabilia' },
	{ '_id': 'Movie Reviews & Previews' },
	{ '_id': 'Musical Films' },
	{ '_id': 'Music & Audio' },
	{ '_id': 'CD & Audio Shopping' },
	{ '_id': 'Classical Music' },
	{ '_id': 'Music Art & Memorabilia' },
	{ '_id': 'Music Education & Instruction' },
	{ '_id': 'Music Equipment & Technology' },
	{ '_id': 'Musical Instruments' },
	{ '_id': 'Music Samples & Sound Libraries' },
	{ '_id': 'Music Composition & Theory' },
	{ '_id': 'Song Lyrics & Tabs' },
	{ '_id': 'Music Streams & Downloads' },
	{ '_id': 'Music Videos' },
	{ '_id': 'Radio' },
	{ '_id': 'Soundtracks' },
	{ '_id': 'Online Media' },
	{ '_id': 'Online Image Galleries' },
	{ '_id': 'Webcams & Virtual Tours' },
	{ '_id': 'Performing Arts' },
	{ '_id': 'Online Video' },
	{ '_id': 'TV Guides & Reference' },
	{ '_id': 'TV Networks & Stations' },
	{ '_id': 'TV Shows & Programs' },
	{ '_id': 'Visual Art & Design' },
	{ '_id': 'Architecture' },
	{ '_id': 'Art & Craft Supplies' },
	{ '_id': 'Art Museums & Galleries' },
	{ '_id': 'Celebrities & Entertainment News' },
	{ '_id': 'Comics' },
	{ '_id': 'Anime & Manga' },
	{ '_id': 'Cartoons' },
	{ '_id': 'Film & TV Industry' },
	{ '_id': 'Music Awards' },
	{ '_id': 'Record Labels' },
	{ '_id': 'Bars, Clubs & Nightlife' },
	{ '_id': 'Concerts & Music Festivals' },
	{ '_id': 'Event Ticket Sales' },
	{ '_id': 'Expos & Conventions' },
	{ '_id': 'Film Festivals' },
	{ '_id': 'Food & Beverage Events' },
	{ '_id': 'Live Sporting Events' },
	{ '_id': 'Movie Listings & Theater Showtimes' },
	{ '_id': 'Fun & Trivia' },
	{ '_id': 'Flash-Based Entertainment' },
	{ '_id': 'Humor' },
	{ '_id': 'Movies' },
	{ '_id': 'Animated Movies' },
	{ '_id': 'Bollywood & South Asian Film' },
	{ '_id': 'Silent Films' },
	{ '_id': 'DVD & Video Shopping' },
	{ '_id': 'Movie Memorabilia' },
	{ '_id': 'Movie Reviews & Previews' },
	{ '_id': 'Musical Films' },
	{ '_id': 'Music & Audio' },
	{ '_id': 'CD & Audio Shopping' },
	{ '_id': 'Classical Music' },
	{ '_id': 'Music Art & Memorabilia' },
	{ '_id': 'Music Education & Instruction' },
	{ '_id': 'Music Equipment & Technology' },
	{ '_id': 'Musical Instruments' },
	{ '_id': 'Music Samples & Sound Libraries' },
	{ '_id': 'Music Composition & Theory' },
	{ '_id': 'Song Lyrics & Tabs' },
	{ '_id': 'Music Streams & Downloads' },
	{ '_id': 'Music Videos' },
	{ '_id': 'Radio' },
	{ '_id': 'Soundtracks' },
	{ '_id': 'Online Media' },
	{ '_id': 'Online Image Galleries' },
	{ '_id': 'Webcams & Virtual Tours' },
	{ '_id': 'Performing Arts' },
	{ '_id': 'Online Video' },
	{ '_id': 'TV Guides & Reference' },
	{ '_id': 'TV Networks & Stations' },
	{ '_id': 'TV Shows & Programs' },
	{ '_id': 'Visual Art & Design' },
	{ '_id': 'Architecture' },
	{ '_id': 'Art & Craft Supplies' },
	{ '_id': 'Art Museums & Galleries' },
	{ '_id': 'Celebrities & Entertainment News' },
	{ '_id': 'Comics' },
	{ '_id': 'Anime & Manga' },
	{ '_id': 'Cartoons' },
	{ '_id': 'Film & TV Industry' },
	{ '_id': 'Music Awards' },
	{ '_id': 'Record Labels' },
	{ '_id': 'Bars, Clubs & Nightlife' },
	{ '_id': 'Concerts & Music Festivals' },
	{ '_id': 'Event Ticket Sales' },
	{ '_id': 'Expos & Conventions' },
	{ '_id': 'Film Festivals' },
	{ '_id': 'Food & Beverage Events' },
	{ '_id': 'Live Sporting Events' },
	{ '_id': 'Movie Listings & Theater Showtimes' },
	{ '_id': 'Fun & Trivia' },
	{ '_id': 'Flash-Based Entertainment' },
	{ '_id': 'Humor' },
	{ '_id': 'Movies' },
	{ '_id': 'Animated Movies' },
	{ '_id': 'Bollywood & South Asian Film' },
	{ '_id': 'Silent Films' },
	{ '_id': 'DVD & Video Shopping' },
	{ '_id': 'Movie Memorabilia' },
	{ '_id': 'Movie Reviews & Previews' },
	{ '_id': 'Musical Films' },
	{ '_id': 'Music & Audio' },
	{ '_id': 'CD & Audio Shopping' },
	{ '_id': 'Classical Music' },
	{ '_id': 'Music Art & Memorabilia' },
	{ '_id': 'Music Education & Instruction' },
	{ '_id': 'Music Equipment & Technology' },
	{ '_id': 'Musical Instruments' },
	{ '_id': 'Music Samples & Sound Libraries' },
	{ '_id': 'Music Composition & Theory' },
	{ '_id': 'Song Lyrics & Tabs' },
	{ '_id': 'Music Streams & Downloads' },
	{ '_id': 'Music Videos' },
	{ '_id': 'Radio' },
	{ '_id': 'Soundtracks' },
	{ '_id': 'Online Media' },
	{ '_id': 'Online Image Galleries' },
	{ '_id': 'Webcams & Virtual Tours' },
	{ '_id': 'Performing Arts' },
	{ '_id': 'Online Video' },
	{ '_id': 'TV Guides & Reference' },
	{ '_id': 'TV Networks & Stations' },
	{ '_id': 'TV Shows & Programs' },
	{ '_id': 'Visual Art & Design' },
	{ '_id': 'Architecture' },
	{ '_id': 'Art & Craft Supplies' },
	{ '_id': 'Art Museums & Galleries' },
	{ '_id': 'Arts Education' },
	{ '_id': 'Graphic Design' },
	{ '_id': 'Industrial & Product Design' },
	{ '_id': 'Interior Design' },
	{ '_id': 'Painting' },
	{ '_id': 'Photographic & Digital Arts' },
	{ '_id': 'Autos & Vehicles' },
	{ '_id': 'Bicycles & Accessories' },
	{ '_id': 'Boats & Watercraft' },
	{ '_id': 'Campers & RVs' },
	{ '_id': 'Classic Vehicles' },
	{ '_id': 'Hybrid & Alternative Vehicles' },
	{ '_id': 'Motorcycles' },
	{ '_id': 'Off-Road Vehicles' },
	{ '_id': 'Scooters & Mopeds' },
	{ '_id': 'Trucks & SUVs' },
	{ '_id': 'Vehicle Codes & Driving Laws' },
	{ '_id': 'Vehicle Maintenance' },
	{ '_id': 'Vehicle Parts & Accessories' },
	{ '_id': 'Vehicle Shopping' },
	{ '_id': 'Vehicle Shows' },
	{ '_id': 'Body Art' },
	{ '_id': 'Cosmetic Procedures' },
	{ '_id': 'Face & Body Care' },
	{ '_id': 'Skin & Nail Care' },
	{ '_id': 'Perfumes & Fragrances' },
	{ '_id': 'Make-Up & Cosmetics' },
	{ '_id': 'Fashion & Style' },
	{ '_id': 'Fitness Equipment & Accessories' },
	{ '_id': 'Fitness Instruction & Personal Training' },
	{ '_id': 'Gyms & Health Clubs' },
	{ '_id': 'Hair Care' },
	{ '_id': 'Spas & Beauty Services' },
	{ '_id': 'Weight Loss' },
	{ '_id': 'Book Retailers' },
	{ '_id': 'E-Books' },
	{ '_id': 'Magazines' },
	{ '_id': 'Advertising & Marketing' },
	{ '_id': 'Promotional Items & Corporate Gifts' },
	{ '_id': 'Agriculture & Forestry' },
	{ '_id': 'Automotive Industry' },
	{ '_id': 'Business Education' },
	{ '_id': 'Business Finance' },
	{ '_id': 'Business Operations' },
	{ '_id': 'Business Services' },
	{ '_id': 'Construction & Maintenance' },
	{ '_id': 'Energy & Utilities' },
	{ '_id': 'Hospitality Industry' },
	{ '_id': 'Industrial Materials & Equipment' },
	{ '_id': 'Manufacturing' },
	{ '_id': 'Pharmaceuticals & Biotech' },
	{ '_id': 'Printing & Publishing' },
	{ '_id': 'Retail Trade' },
	{ '_id': 'Textiles & Nonwovens' },
	{ '_id': 'Transportation & Logistics' },
	{ '_id': 'Computers & Electronics' },
	{ '_id': 'Computer Hardware' },
	{ '_id': 'Computer Drives & Storage' },
	{ '_id': 'Computer Peripherals' },
	{ '_id': 'Computer Servers' },
	{ '_id': 'Desktop Computers' },
	{ '_id': 'Hardware Modding & Tuning' },
	{ '_id': 'Laptops & Notebooks' },
	{ '_id': 'Computer Security' },
	{ '_id': 'Consumer Electronics' },
	{ '_id': 'Camera & Photo Equipment' },
	{ '_id': 'Car Electronics' },
	{ '_id': 'Gadgets & Portable Electronics' },
	{ '_id': 'Game Systems & Consoles' },
	{ '_id': 'TV & Video Equipment' },
	{ '_id': 'Enterprise Technology' },
	{ '_id': 'Networking' },
	{ '_id': 'Programming' },
	{ '_id': 'Software' },
	{ '_id': 'Accounting & Auditing' },
	{ '_id': 'Banking' },
	{ '_id': 'Credit & Lending' },
	{ '_id': 'Financial Planning & Management' },
	{ '_id': 'Insurance' },
	{ '_id': 'Investing' },
	{ '_id': 'Exchanges' },
	{ '_id': 'Stocks & Bonds' },
	{ '_id': 'Food & Drink' },
	{ '_id': 'Beverages' },
	{ '_id': 'Cooking & Recipes' },
	{ '_id': 'Grocery Delivery' },
	{ '_id': 'Restaurants' },
	{ '_id': 'Games' },
	{ '_id': 'Computer & Video Games' },
	{ '_id': 'Game Cheats & Hints' },
	{ '_id': 'Sports Games' },
	{ '_id': 'Strategy Games' },
	{ '_id': 'Video Game Development' },
	{ '_id': 'Video Game Retailers' },
	{ '_id': 'Educational Games' },
	{ '_id': 'Family-Oriented Games & Activities' },
	{ '_id': 'Online Games' },
	{ '_id': 'Puzzles & Brainteasers' },
	{ '_id': 'Health' },
	{ '_id': 'Health Education & Medical Training' },
	{ '_id': 'Medical Devices & Equipment' },
	{ '_id': 'Medical Facilities & Services' },
	{ '_id': 'Medical Literature & Resources' },
	{ '_id': 'Nutrition' },
	{ '_id': 'Oral & Dental Care' },
	{ '_id': 'Hobbies & Leisure' },
	{ '_id': 'Clubs & Organizations' },
	{ '_id': 'Contests, Awards & Prizes' },
	{ '_id': 'Crafts' },
	{ '_id': 'Radio Control & Modeling' },
	{ '_id': 'Weddings' },
	{ '_id': 'Home & Garden' },
	{ '_id': 'Home Improvement' },
	{ '_id': 'Internet & Telecom' },
	{ '_id': 'Web Apps & Online Tools' },
	{ '_id': 'Web Portals' },
	{ '_id': 'Web Services' },
	{ '_id': 'Education' },
	{ '_id': 'Jobs' },
	{ '_id': 'Job Listings' },
	{ '_id': 'Government' },
	{ '_id': 'Legal' },
	{ '_id': 'Social Services' },
	{ '_id': 'Broadcast & Network News' },
	{ '_id': 'Gossip & Tabloid News' },
	{ '_id': 'Newspapers' },
	{ '_id': 'Sports News' },
	{ '_id': 'Weather' },
	{ '_id': 'Technology News' },
	{ '_id': 'Blogging Resources & Services' },
	{ '_id': 'Dating & Personals' },
	{ '_id': 'File Sharing & Hosting' },
	{ '_id': 'Clip Art & Animated GIFs' },
	{ '_id': 'Social Network Apps & Add-Ons' },
	{ '_id': 'Photo & Video Sharing' },
	{ '_id': 'Social Networks' },
	{ '_id': 'People & Society' },
	{ '_id': 'Religion & Belief' },
	{ '_id': 'Subcultures & Niche Interests' },
	{ '_id': 'Animal Products & Services' },
	{ '_id': 'Pets' },
	{ '_id': 'Real Estate' },
	{ '_id': 'Directories & Listings' },
	{ '_id': 'Forms Guides & Templates' },
	{ '_id': 'Educational Resources' },
	{ '_id': 'How-To, DIY & Expert Content' },
	{ '_id': 'City & Local Guides' },
	{ '_id': 'History' },
	{ '_id': 'Myth & Folklore' },
	{ '_id': 'Foreign Language Resources' },
	{ '_id': 'Libraries & Museums' },
	{ '_id': 'Technical Reference' },
	{ '_id': 'Science' },
	{ '_id': 'Astronomy' },
	{ '_id': 'Biological Sciences' },
	{ '_id': 'Chemistry' },
	{ '_id': 'Computer Science' },
	{ '_id': 'Earth Sciences' },
	{ '_id': 'Ecology & Environment' },
	{ '_id': 'Engineering & Technology' },
	{ '_id': 'Mathematics' },
	{ '_id': 'Physics' },
	{ '_id': 'Scientific Equipment' },
	{ '_id': 'Scientific Institutions' },
	{ '_id': 'Shopping' },
	{ '_id': 'Antiques & Collectibles' },
	{ '_id': "Children's Clothing" },
	{ '_id': 'Clothing Accessories' },
	{ '_id': 'Gems & Jewelry' },
	{ '_id': "Men's Clothing" },
	{ '_id': "Women's Clothing" },
	{ '_id': 'Customer Services' },
	{ '_id': 'Coupons & Discount Offers' },
	{ '_id': 'Identity Theft & Protection' },
	{ '_id': 'Product Reviews & Price Comparisons' },
	{ '_id': 'Discount & Outlet Stores' },
	{ '_id': 'Entertainment Media' },
	{ '_id': 'Gifts & Special Event Items' },
	{ '_id': 'Green & Eco-Friendly Shopping' },
	{ '_id': 'Luxury Goods' },
	{ '_id': 'Photo & Video Services' },
	{ '_id': 'Shopping Portals & Search Engines' },
	{ '_id': 'Toys' },
	{ '_id': 'Wholesalers & Liquidators' },
	{ '_id': 'Sports' },
	{ '_id': 'Boxing' },
	{ '_id': 'Martial Arts' },
	{ '_id': 'Wrestling' },
	{ '_id': 'Extreme Sports' },
	{ '_id': 'Bowling' },
	{ '_id': 'Cycling' },
	{ '_id': 'Golf' },
	{ '_id': 'Gymnastics' },
	{ '_id': 'Tennis' },
	{ '_id': 'Running & Walking' },
	{ '_id': 'Skate Sports' },
	{ '_id': 'Motor Sports' },
	{ '_id': 'Sport Scores & Statistics' },
	{ '_id': 'Sporting Goods' },
	{ '_id': 'Sports Memorabilia' },
	{ '_id': 'Sports Coaching & Training' },
	{ '_id': 'American Football' },
	{ '_id': 'Australian Football' },
	{ '_id': 'Baseball' },
	{ '_id': 'Basketball' },
	{ '_id': 'Cheerleading' },
	{ '_id': 'Cricket' },
	{ '_id': 'Handball' },
	{ '_id': 'Hockey' },
	{ '_id': 'Rugby' },
	{ '_id': 'Soccer' },
	{ '_id': 'Volleyball' },
	{ '_id': 'Surfing' },
	{ '_id': 'Swimming' },
	{ '_id': 'Ice Skating' },
	{ '_id': 'Skiing & Snowboarding' },
	{ '_id': 'World Sports Competitions' },
	{ '_id': 'Olympics' },
	{ '_id': 'Travel' },
	{ '_id': 'Car Rental & Taxi Services' },
	{ '_id': 'Cruises & Charters' },
	{ '_id': 'Hotels & Accommodations' },
	{ '_id': 'Luggage & Travel Accessories' },
	{ '_id': 'Adventure Travel' },
	{ '_id': 'Agritourism' },
	{ '_id': 'Ecotourism' },
	{ '_id': 'Sightseeing Tours' },
	{ '_id': 'Vineyards & Wine Tourism' },
	{ '_id': 'Beaches & Islands' },
	{ '_id': 'Historical Sites & Buildings' },
	{ '_id': 'Lakes & Rivers' },
	{ '_id': 'Mountain & Ski Resorts' },
	{ '_id': 'Regional Parks & Gardens' },
	{ '_id': 'Theme Parks' },
	{ '_id': 'Zoos-Aquariums-Preserves' },
	{ '_id': 'Travel Agencies & Services' },
	{ '_id': 'Travel Guides & Travelogues' },
	{ '_id': 'ICO' },
	{ '_id': 'Cryptocurrency' },
	{ '_id': 'Crypto Еxchange' },
	{ '_id': 'Blockchain' },
	{ '_id': 'Crypto FinTech' },
	{ '_id': '' },
	{ '_id': '' },
	{ '_id': 'World Localities' },
	{ '_id': 'Africa' },
	{ '_id': 'Ethiopia' },
	{ '_id': 'Kenya' },
	{ '_id': 'Madagascar' },
	{ '_id': 'Malawi' },
	{ '_id': 'Mozambique' },
	{ '_id': 'Rwanda' },
	{ '_id': 'Somalia' },
	{ '_id': 'Tanzania' },
	{ '_id': 'Uganda' },
	{ '_id': 'Zambia' },
	{ '_id': 'Zimbabwe' },
	{ '_id': 'Angola' },
	{ '_id': 'Cameroon' },
	{ '_id': 'Chad' },
	{ '_id': 'Congo (DR)' },
	{ '_id': 'Algeria' },
	{ '_id': 'Egypt' },
	{ '_id': 'Libya' },
	{ '_id': 'Morocco' },
	{ '_id': 'Sudan' },
	{ '_id': 'Tunisia' },
	{ '_id': 'Botswana' },
	{ '_id': 'South Africa' },
	{ '_id': 'Burkina Faso' },
	{ '_id': "Côte d'Ivoire" },
	{ '_id': 'Ghana' },
	{ '_id': 'Mali' },
	{ '_id': 'Niger' },
	{ '_id': 'Nigeria' },
	{ '_id': 'Senegal' },
	{ '_id': 'Asia' },
	{ '_id': 'Kazakhstan' },
	{ '_id': 'Kyrgyzstan' },
	{ '_id': 'Tajikistan' },
	{ '_id': 'Turkmenistan' },
	{ '_id': 'Uzbekistan' },
	{ '_id': 'China' },
	{ '_id': 'Eastern China' },
	{ '_id': 'North Central China' },
	{ '_id': 'Northeast China' },
	{ '_id': 'South Central China' },
	{ '_id': 'Southeast China' },
	{ '_id': 'Southwest China' },
	{ '_id': 'Hong Kong' },
	{ '_id': 'Japan' },
	{ '_id': 'Macau' },
	{ '_id': 'Mongolia' },
	{ '_id': 'North Korea' },
	{ '_id': 'South Korea' },
	{ '_id': 'Taiwan' },
	{ '_id': 'Armenia' },
	{ '_id': 'Azerbaijan' },
	{ '_id': 'Georgia' },
	{ '_id': 'Russian Federation' },
	{ '_id': 'Far Eastern Russia' },
	{ '_id': 'Northwestern Russia' },
	{ '_id': 'Russian Central District' },
	{ '_id': 'Russian Southern District' },
	{ '_id': 'Russian Federation - Siberian Federal District' },
	{ '_id': 'Russian Federation - Urals District' },
	{ '_id': 'Russian Federation - Volga District' },
	{ '_id': 'Afghanistan' },
	{ '_id': 'Bangladesh' },
	{ '_id': 'Bhutan' },
	{ '_id': 'India' },
	{ '_id': 'East India' },
	{ '_id': 'North India' },
	{ '_id': 'Northeast India' },
	{ '_id': 'South India' },
	{ '_id': 'West India' },
	{ '_id': 'Indian Ocean Islands' },
	{ '_id': 'Maldives' },
	{ '_id': 'Réunion' },
	{ '_id': 'Nepal' },
	{ '_id': 'Pakistan' },
	{ '_id': 'Sri Lanka' },
	{ '_id': 'Brunei' },
	{ '_id': 'Cambodia' },
	{ '_id': 'East Timor' },
	{ '_id': 'Indonesia' },
	{ '_id': 'Laos' },
	{ '_id': 'Malaysia' },
	{ '_id': 'Myanmar' },
	{ '_id': 'Philippines' },
	{ '_id': 'Singapore' },
	{ '_id': 'Thailand' },
	{ '_id': 'Vietnam' },
	{ '_id': 'Bahrain' },
	{ '_id': 'Iran' },
	{ '_id': 'Iraq' },
	{ '_id': 'Israel' },
	{ '_id': 'Jordan' },
	{ '_id': 'Kuwait' },
	{ '_id': 'Lebanon' },
	{ '_id': 'Oman' },
	{ '_id': 'Qatar' },
	{ '_id': 'Saudi Arabia' },
	{ '_id': 'Syria' },
	{ '_id': 'Turkey' },
	{ '_id': 'Aegean Turkey' },
	{ '_id': 'Black Sea Turkey' },
	{ '_id': 'Turkey - Central Anatolia' },
	{ '_id': 'Turkey - Eastern Anatolia' },
	{ '_id': 'Turkey - Marmara Region' },
	{ '_id': 'Mediterranean Turkey' },
	{ '_id': 'Turkey - Southeastern Anatolia' },
	{ '_id': 'United Arab Emirates' },
	{ '_id': 'Yemen' },
	{ '_id': 'Europe' },
	{ '_id': 'Austria' },
	{ '_id': 'Estonia' },
	{ '_id': 'Latvia' },
	{ '_id': 'Lithuania' },
	{ '_id': 'Czech Republic' },
	{ '_id': 'Belarus' },
	{ '_id': 'Moldova' },
	{ '_id': 'Ukraine' },
	{ '_id': 'Germany' },
	{ '_id': 'Hungary' },
	{ '_id': 'Liechtenstein' },
	{ '_id': 'Poland' },
	{ '_id': 'Slovakia' },
	{ '_id': 'Slovenia' },
	{ '_id': 'Switzerland' },
	{ '_id': 'Cyprus' },
	{ '_id': 'Italy' },
	{ '_id': 'Sardinia' },
	{ '_id': 'Sicily' },
	{ '_id': 'Malta' },
	{ '_id': 'Monaco' },
	{ '_id': 'Portugal' },
	{ '_id': 'Azores & Madeira' },
	{ '_id': 'San Marino' },
	{ '_id': 'Spain' },
	{ '_id': 'Vatican City' },
	{ '_id': 'Denmark' },
	{ '_id': 'Finland' },
	{ '_id': 'Greenland' },
	{ '_id': 'Iceland' },
	{ '_id': 'Norway' },
	{ '_id': 'Sweden' },
	{ '_id': 'Albania' },
	{ '_id': 'Bosnia and Herzegovina' },
	{ '_id': 'Bulgaria' },
	{ '_id': 'Croatia' },
	{ '_id': 'Greece' },
	{ '_id': 'Kosovo' },
	{ '_id': 'Montenegro' },
	{ '_id': 'Republic of Macedonia' },
	{ '_id': 'Romania' },
	{ '_id': 'Serbia' },
	{ '_id': 'Andorra' },
	{ '_id': 'Belgium' },
	{ '_id': 'Luxembourg' },
	{ '_id': 'Netherlands' },
	{ '_id': 'France' },
	{ '_id': 'Central France' },
	{ '_id': 'East France' },
	{ '_id': 'French Overseas (DOM-TOM)' },
	{ '_id': 'North France' },
	{ '_id': 'South East France' },
	{ '_id': 'South West France' },
	{ '_id': 'West France' },
	{ '_id': 'Île-de-France' },
	{ '_id': 'Ireland' },
	{ '_id': 'United Kingdom' },
	{ '_id': 'England' },
	{ '_id': 'Northern Ireland' },
	{ '_id': 'Scotland' },
	{ '_id': 'Wales' },
	{ '_id': 'Latin America' },
	{ '_id': 'Antigua & Barbuda' },
	{ '_id': 'Aruba, Bonaire & Curaçao' },
	{ '_id': 'Bahamas' },
	{ '_id': 'Barbados' },
	{ '_id': 'Cayman Islands' },
	{ '_id': 'Cuba' },
	{ '_id': 'Dominica' },
	{ '_id': 'Dominican Republic' },
	{ '_id': 'Grenada' },
	{ '_id': 'Guadeloupe' },
	{ '_id': 'Haiti' },
	{ '_id': 'Jamaica' },
	{ '_id': 'Martinique' },
	{ '_id': 'Puerto Rico' },
	{ '_id': 'Saint Kitts & Nevis' },
	{ '_id': 'Saint Lucia' },
	{ '_id': 'Saint Vincent & Grenadines' },
	{ '_id': 'Trinidad & Tobago' },
	{ '_id': 'Virgin Islands' },
	{ '_id': 'Belize' },
	{ '_id': 'Costa Rica' },
	{ '_id': 'El Salvador' },
	{ '_id': 'Guatemala' },
	{ '_id': 'Honduras' },
	{ '_id': 'Mexico' },
	{ '_id': 'Nicaragua' },
	{ '_id': 'Panama' },
	{ '_id': 'Argentina' },
	{ '_id': 'Bolivia' },
	{ '_id': 'Brazil' },
	{ '_id': 'Central West Brazil' },
	{ '_id': 'North Brazil' },
	{ '_id': 'Northeast Brazil' },
	{ '_id': 'South Brazil' },
	{ '_id': 'Southeast Brazil' },
	{ '_id': 'Chile' },
	{ '_id': 'Colombia' },
	{ '_id': 'Ecuador' },
	{ '_id': 'French Guiana' },
	{ '_id': 'Guyana' },
	{ '_id': 'Paraguay' },
	{ '_id': 'Peru' },
	{ '_id': 'Suriname' },
	{ '_id': 'Uruguay' },
	{ '_id': 'Venezuela' },
	{ '_id': 'Middle East' },
	{ '_id': 'North America' },
	{ '_id': 'Bermuda' },
	{ '_id': 'Canada' },
	{ '_id': 'Canada - Atlantic Provinces' },
	{ '_id': 'Canada - British Columbia' },
	{ '_id': 'Canadian Prairies' },
	{ '_id': 'Canada - Northern Territories' },
	{ '_id': 'Canada - Ontario' },
	{ '_id': 'Canada - Quebec' },
	{ '_id': 'USA' },
	{ '_id': 'Alaska' },
	{ '_id': 'California' },
	{ '_id': 'Florida' },
	{ '_id': 'Kansas' },
	{ '_id': 'Nebraska' },
	{ '_id': 'North Dakota' },
	{ '_id': 'Oklahoma' },
	{ '_id': 'South Dakota' },
	{ '_id': 'Hawaii' },
	{ '_id': 'Delaware' },
	{ '_id': 'Maryland' },
	{ '_id': 'New Jersey' },
	{ '_id': 'New York State' },
	{ '_id': 'Pennsylvania' },
	{ '_id': 'Washington DC' },
	{ '_id': 'Illinois' },
	{ '_id': 'Indiana' },
	{ '_id': 'Iowa' },
	{ '_id': 'Michigan' },
	{ '_id': 'Minnesota' },
	{ '_id': 'Missouri' },
	{ '_id': 'Ohio' },
	{ '_id': 'Wisconsin' },
	{ '_id': 'Connecticut' },
	{ '_id': 'Maine' },
	{ '_id': 'Massachusetts' },
	{ '_id': 'New Hampshire' },
	{ '_id': 'Rhode Island' },
	{ '_id': 'Vermont' },
	{ '_id': 'Oregon' },
	{ '_id': 'Washington State' },
	{ '_id': 'Colorado' },
	{ '_id': 'Idaho' },
	{ '_id': 'Montana' },
	{ '_id': 'Wyoming' },
	{ '_id': 'Alabama' },
	{ '_id': 'Arkansas' },
	{ '_id': 'Georgia (USA)' },
	{ '_id': 'Kentucky' },
	{ '_id': 'Louisiana' },
	{ '_id': 'Mississippi' },
	{ '_id': 'North Carolina' },
	{ '_id': 'South Carolina' },
	{ '_id': 'Tennessee' },
	{ '_id': 'Virginia' },
	{ '_id': 'West Virginia' },
	{ '_id': 'Arizona' },
	{ '_id': 'Nevada' },
	{ '_id': 'New Mexico' },
	{ '_id': 'Utah' },
	{ '_id': 'Texas' },
	{ '_id': 'Australia' },
	{ '_id': 'New Zealand' },
	{ '_id': 'Pacific Islands' },
	{ '_id': 'Polar Regions' }]

const uniqueTags = Object.values(tags.reduce((memo, tag, index) => {
	let id = tag._id
	if (id) {
		// TODO: fix tags regex to accept some other chars used here
		id = id.toLowerCase().trim()
		memo[id] = id
	}
	return memo
}, {}))

const PredefinedTags = (uniqueTags.sort((a, b) => {
	if (a < b) {
		return -1
	} else if (a > b) {
		return 1
	}
	return 0
})).map((tag) => {
	return { _id: tag }
})

module.exports = {
	PredefinedTags: PredefinedTags
}
